# Message Service
## Message Collection [/api/getperson]
### GET Messages Collection [GET]
+ Response 200 (text/plain)
    + Headers
        Cache-Control: max-age=86400
    + Body
        Hello World!